### ISSUE TITLE
An error message with CAMLU function 

### ISSUE THREAD

**Issue by zyb1984** [ziyili20/CAMLU#2]
Dear professor,
     I tried to follow the basic tutorial  on "https://github.com/ziyili20/CAMLU", but with error message on  CAMLU function, and error message is "Error: Python module tensorflow.keras was not found. ", and detail infromation    
library(CAMLU)
> label_01 <- CAMLU(x_train = simdata$fdata_train,
+                   x_test = simdata$fdata_test,
+                   ngene=5000,lognormalize=TRUE)
Number of overlapped genes in training and testing dataset:6417.
Number of selected high variance gene is less than specified ngene:4595.
List of 20
 $ python              : chr "C:/ProgramData/Anaconda3/envs/r-reticulate/python.exe"
 $ libpython           : chr "C:/ProgramData/Anaconda3/envs/r-reticulate/python39.dll"
 $ pythonhome          : chr "C:/ProgramData/Anaconda3/envs/r-reticulate"
 $ pythonpath          : chr "C:\\PROGRA~3\\ANACON~1\\envs\\R-RETI~1\\python39.zip;C:\\PROGRA~3\\ANACON~1\\envs\\R-RETI~1\\DLLs;C:\\PROGRA~3\"| __truncated__
 $ prefix              : chr "C:\\PROGRA~3\\ANACON~1\\envs\\R-RETI~1"
 $ exec_prefix         : chr "C:\\PROGRA~3\\ANACON~1\\envs\\R-RETI~1"
 $ base_exec_prefix    : chr "C:\\PROGRA~3\\ANACON~1\\envs\\R-RETI~1"
 $ virtualenv          : chr ""
 $ virtualenv_activate : chr ""
 $ version_string      : chr "3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]"
 $ version             : chr "3.9"
 $ architecture        : chr "64bit"
 $ anaconda            : logi FALSE
 $ conda               : logi FALSE
 $ numpy               :List of 2
  ..$ path   : chr "C:/ProgramData/Anaconda3/envs/r-reticulate/Lib/site-packages/numpy"
  ..$ version:Class 'numeric_version'  hidden list of 1
  .. ..$ : int [1:3] 1 22 3
 $ required_module     : chr "tensorflow"
 $ required_module_path: chr "C:\\PROGRA~3\\ANACON~1\\envs\\R-RETI~1\\lib\\site-packages\\tensorflow\\__init__.p"
 $ available           : logi TRUE
 $ python_versions     : chr [1:3] "C:/ProgramData/Anaconda3/envs/r-reticulate/python.exe" "C:/ProgramData/Anaconda3/python.exe" "C:/Users/zhangyingbo1984/AppData/Local/R/cache/R/basilisk/1.8.0/0/python.exe"
 $ forced              : NULL
 - attr(*, "class")= chr "py_config"
Error: Python module tensorflow.keras was not found.
Detected Python configuration:
      Also with tensorflow had been sucessfully installed on r-reticulate environment, and with information 

![image](https://user-images.githubusercontent.com/24197491/192092763-175569d1-1b98-42bd-974f-4b411e6d7e17.png)

    and How to solve this problem ?

**Comment by abedkurdi** [comment]
this package relies on `keras` installed as R package. It does not seem to be using the `python` version installed on your system. Try this: `install.packages('keras')`.

**Comment by ziyili20** [comment]
Yes, I echo the reply from @abedkurdi. Please install keras (https://cran.r-project.org/web/packages/keras/index.html) through `install.packages('keras')`.
