### ISSUE TITLE
Error: objects ‘rowSums’, ‘colSums’, ‘rowMeans’, ‘colMeans’ are not exported by 'namespace:BiocGenerics'

### ISSUE THREAD

**Issue by akhst7** [ziyili20/CAMLU#4]
CAMLU failed to build in my M1 Mac with a following error;

```
Running `R CMD build`...
* checking for file ‘/private/var/folders/qp/qm7rgfps34v9p46d6mr3_80h0000gn/T/RtmpRFlH4B/remotesd3b53fb6182/ziyili20-CAMLU-5060283/DESCRIPTION’ ... OK
* preparing ‘CAMLU’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘CAMLU_0.1.0.tar.gz’
Installing package into ‘/Volumes/Document/4.3.X_Rlib’
(as ‘lib’ is unspecified)
* installing *source* package ‘CAMLU’ ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Error: objects ‘rowSums’, ‘colSums’, ‘rowMeans’, ‘colMeans’ are not exported by 'namespace:BiocGenerics'
Execution halted
ERROR: lazy loading failed for package ‘CAMLU’
* removing ‘/Volumes/Document/4.3.X_Rlib/CAMLU’
```

I have Biogenrics;

```
packageVersion("BiocGenerics")
[1] ‘0.45.3’
```
Please, let me know workaround for this issue. 

```
R.version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          3.0                         
year           2023                        
month          04                          
day            21                          
svn rev        84292                       
language       R                           
version.string R version 4.3.0 (2023-04-21)
nickname       Already Tomorrow 
```

**Comment by ziyili20** [comment]
Hello, I couldn't reproduce the error. But I did some search and found that this issue can happen when multiple versions of bioconductor packages are running. See the discussions in:
https://community.rstudio.com/t/deseq2-error-package-or-namespace-load-failed-for-deseq2-objects-rowsums-colsums-rowmeans-colmeans-are-not-exported-by-namespace-s4vectors/77759
https://github.com/statOmics/tradeSeq/issues/49
https://support.bioconductor.org/p/129912/

**Comment by akhst7** [comment]
@ziyili20, what is a BioGenerics version in your R ?

**Comment by ziyili20** [comment]
Mine is 0.42.0.

**Comment by akhst7** [comment]
So mine is 0.43.5   There may be an issue with BioGenerics interfering with R base rowSums ... functions.  I have not looked at your code carefully but how are rowSums and others called ? BioGenerics does not have these functions as far as I know.

**Comment by ziyili20** [comment]
I checked all the functions. Only one function `PrepFunc` used rowSums() in
the first step:
[image: Screen Shot 2023-04-28 at 9.33.14 AM.png]
Throughout the package, we didn't import BioGenerics anywhere. Do you want
to open a clean R and re-install the package? I don't think this is a
problem in the package itself, as I tried on different computers and
haven't run into similar issues.

**Comment by akhst7** [comment]
@ziyili20, I figured this out.  It was an old recurring issue with findMatches and AnnotationDbi which for some reasons calls BioGenerics, thinking it provides rowSums....etc and probably conflicting with sv4Vector.  I am still not sure how this happens but I dont care since CAMLU installed without a hitch. 

thanks.
